config/routes.rb
Rails.application.routes.draw do
  root 'payment#index'
  post 'pay', to: 'payment#pay'
  post 'capture', to: 'payment#capture'
  get 'error', to: 'payment#error'
  get 'success', to: 'payment#success'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  def index
  end

  def pay 
    paymongo = Paymongo::V1::CardPayment.new
    amount = params[:amount].to_i * 100
    message = params[:message]

    begin 
      @payment_intent = paymongo.create_payment_intent(amount, message)
    rescue ApiExceptions::BadRequest
      redirect_to error_path
    end
  end

  def capture 
    payment_intent_id = params[:payment_intent_id]
    client_key = params[:client_key]
    card_details = {
      card_number: params[:card_number], 
      exp_month: params[:exp_month].to_i, 
      exp_year: params[:exp_year].to_i, 
      cvc: params[:cvc]
    }
    billing = {
      name: params[:name],
      email: params[:email]
    }

    paymongo = Paymongo::V1::CardPayment.new

    begin 
      @payment_method = paymongo.create_payment_method(card_details, billing)
    rescue ApiExceptions::BadRequest
      redirect_to error_path
    end
    
    payment_method_id = @payment_method['data']['id']
    
    begin 
      @response = paymongo.attach(
        payment_intent_id, 
        payment_method_id, 
        client_key
      )
    rescue ApiExceptions::BadRequest
      redirect_to error_path
    end
    
    redirect_to success_path 
  end

  def success 
  end

  def error 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apiwrapper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
      
      <footer>
        <small>&copy; 2022 DonateToProgrammers. All rights reserved.</small>
      </footer>
    </main>
    
  </body>
</html>

app/views/payment/error.html.erb
<div class='container text-center'>
  <h1>Something broke...</h1>
  <%= image_tag 'worried.svg', :class => 'img' %>
  <p>Don't worry. It's our fault. Your card is not charged.</p>
  <%= button_to 'Try again', root_path, :method => :get %>
</div>

app/views/payment/index.html.erb
<div class='container text-center'>
  <h1>Please donate?</h1>
  <%= image_tag 'starving.svg', :class => 'img' %>
  <p>Help feed starving programmers in the Philippines.</p>
  <%= form_with url: pay_path do |f| %>
    <%= f.number_field :amount, placeholder: '&#8369;'.html_safe, :required => true %>
    <%= f.text_field :message, placeholder: 'Your message...', :required => true %>
    <%= f.submit 'Send money' %>
  <% end %>
</div>

app/views/payment/pay.html.erb
<div class='container'>
  <h1 class='text-center'>Payment details</h1>
  <%= form_with url: capture_path do |f| %>
    <%= f.hidden_field :payment_intent_id, value: @payment_intent['data']['id'] %>
    <%= f.hidden_field :client_key, value: @payment_intent['data']['attributes']['client_key'] %>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
    <%= f.label :email %>
    <%= f.text_field :email, :required => true %>
    <%= f.label :card_number %>
    <%= f.text_field :card_number, :required => true %>
    <div class='column'>
      <div class='form-group'>
        <%= f.label :exp_month %>
        <%= f.text_field :exp_month, :required => true %>
      </div>
      <div class='form-group'>
        <%= f.label :exp_year %>
        <%= f.text_field :exp_year, :required => true %>
      </div>
      <div>
        <%= f.label :cvc %>
        <%= f.text_field :cvc, :required => true %>
      </div>
    </div>
    <%= f.submit 'Donate' %>
  <% end %>
  <div class='text-center pt-3'>
    <%= image_tag 'credit-card-logos.png', :class => 'credit-card' %>
  </div>
</div>

app/views/payment/success.html.erb
<div class='container text-center'>
  <h1>Success!</h1>
  <%= image_tag 'eating.svg', :class => 'img' %>
  <p>Because of your donation, a hungry programmer has been fed.</p>
  <%= button_to 'Donate again', root_path, :method => :get %>
</div>